# Generated by Django 4.2.3 on 2023-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
